export default[
    {
        isactivated:0,
        name:'blog',
        git:'https://github.com/anliting/althea-blog.git'
    },
    {
        isactivated:0,
        name:'blog-katex',
        git:'https://github.com/anliting/althea-blog-katex.git'
    },
    {
        isactivated:0,
        name:'blog-syntaxhighlighter',
        git:'https://github.com/anliting/althea-blog-syntaxhighlighter.git'
    },
    {
        isactivated:0,
        name:'blog-webvim',
        git:'https://github.com/anliting/althea-blog-webvim.git'
    },
    {
        isactivated:0,
        name:'blog-graphvisualizer',
        git:'https://github.com/anliting/althea-blog-graphvisualizer.git'
    },
    {
        isactivated:0,
        name:'blog-anlitings-style',
        git:'https://github.com/anliting/althea-blog-anlitings-style.git'
    },
]
