module.exports={
    deleteUser:
        require('./queryFunctions/deleteUser'),
    getCurrentUser:
        require('./queryFunctions/getCurrentUser'),
    getEnvironmentvariables:
        require('./queryFunctions/getEnvironmentvariables'),
    getPluginScripts:
        require('./queryFunctions/getPluginScripts'),
    getPlugins:
        require('./queryFunctions/getPlugins'),
    getUser:
        require('./queryFunctions/getUser'),
    getUserByUsername:
        require('./queryFunctions/getUserByUsername'),
    getUsers:
        require('./queryFunctions/getUsers'),
    newImage:
        require('./queryFunctions/newImage'),
    newUser:
        require('./queryFunctions/newUser'),
    updateEnvironmentvariableById:
        require('./queryFunctions/updateEnvironmentvariableById'),
    updatePluginById:
        require('./queryFunctions/updatePluginById'),
    updateUser:
        require('./queryFunctions/updateUser'),
    login:
        require('./queryFunctions/login'),
    logout:
        require('./queryFunctions/logout'),
}
