module.exports=db=>{
    db.deleteUser=
        require('./loadUserProperties/deleteUser')
    db.getCurrentUser=
        require('./loadUserProperties/getCurrentUser')
    db.getCurrentUserByRequest=
        require('./loadUserProperties/getCurrentUserByRequest')
    db.getSession=
        require('./loadUserProperties/getSession')
    db.getUser=
        require('./loadUserProperties/getUser')
    db.getUsers=
        require('./loadUserProperties/getUsers')
    db.getUserIdByUsername=
        require('./loadUserProperties/getUserIdByUsername')
    db.newUser=
        require('./loadUserProperties/newUser')
    db.login=
        require('./loadUserProperties/login')
}
